<a href="https://colab.research.google.com/github/Bast1-py/Experience-Developing-Projects/blob/main/Text_Clustering_and_Semantic_Similarity_using_NLP_Embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from IPython.display import Image, HTML, display, display_html
source_tautan = "https://skills.network/logos/SN_web_lightmode.png"
HTML(f'<div style="text-align: center;"><img src="{source_tautan}" style="max-width: 600px; height: auto;"></div>')

# **1. Introduction:**

**Sentence-BERT** adalah modifikasi dari framework BERT untuk memungkinkan perbandingan **Large-scale semantic similarity, clustering dan information retrieval.**

**Sentence-BERT** atau **SBERT** menggunakan struktur jaringan **siamese** dan **triplet** untuk menghasilkan embedding kalimat yang bermakna secara semantik yang dapat dibandingkan menggunakan **cosine-similarity**. **siamese network** terdiri dari dua atau lebih sub-jaringan identik, dimana kedua sub-jaringan tersebut berbagi bobot yang sama. pembaruan bobot dicerminkan diseluruh sub-jaringan selama pelatihan. berikut dibawah ini diagram arsitektur SBERT dengan fungsi tujuan klasifikasi:

In [ ]:
from IPython.display import Image, HTML, display, display_html
source_tautan = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-GPXX068IEN/images/SBERT.png"
HTML(f'<div style="text-align: center;"><img src="{source_tautan}" style="max-width: 450px; height: auto;"></div>')

diagram diatas menunjukkan bahwa SBERT menggunakan 2 model BERT "twin" dan menambahkan operasi pooling pada output dari kedua model BERT tersebut. **The pooling layers** menciptakan embedding kalimat berukuran tetap untuk kalimat input.

embedding kalimat adalah bidang yang banyak dipelajari dengan puluhan metode yang diusulkan. metode embedding kalimat sebelumnya seperti **InferSent** dan **Universal Sentence Encoder** dilatih dari random initializations.

para penulis **Sentence-BERT: Sentence Embeddings using Siamese BERT-Networks** menggunakan jaringan **BERT** dan **RoBERTa** yang telah dilatih sebelumnya dan melakukan fine-tuning untuk menghasilkan embedding kalimat, yang secara signifikan menbgurangi waktu pelatihan (SBERT dapat di-tuning dalam waktu kurang dari 20 menit) sambil menghasilkan hasil yang lebih baik daripada metode embedding kalimat yang sebanding.

SBERT memiliki library python bernama sentence_transformers yang dapat digunakan untuk menghitung embedding kalimat untuk lebih dari 100 bahasa. embedding ini kemudian dapat dibandingkan, misalnya, dengan cosine similarity untuk menemukan kalimat dengan makna yang serupa. ini dapat berguna untuk kesamaan teks semantik, semantic search, atau penambahan parafrasa.

pustaka ini menawarkan koleksi dari [pretrained models](https://www.sbert.net/docs/sentence_transformer/pretrained_models.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectsIBMGPXX068IEN1371-2022-01-01) untuk berbagai tugas. misalnya **all-mpnet-base-v2:** memberikan kualitas terbaik, sementara **all-MiniLM-L6-v2:** 5 kali lebih cepat dan tetap menawarkan kualitas yang baik.

# **2. Importing Required Libraries**

In [ ]:
# pip install adjustText

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.graph_objects as go

%matplotlib inline

from adjustText import adjust_text
from numpy.linalg import norm
from sklearn.decomposition import PCA
from sklearn.neighbors import NearestNeighbors
from sklearn.cluster import KMeans
from scipy.stats import gaussian_kde
from sentence_transformers import SentenceTransformer, util

import warnings
warnings.filterwarnings("ignore")

# **3. Defining Helper Functions**

In [ ]:
def plotter(
    x,
    y,
    title):
  plt.plot(x,y)
  plt.xlabel('X')
  plt.ylabel('Y')
  plt.title(title)
  plt.show()

# **4. SBERT For Sentence Embeddings.**

In [ ]:
sentences = [
    'This Framework Generates embeddings For Each Input Sentence.',
    'Sentences Are Passed as a List of String.',
    'The Quick Brown Fox Jumps Over The Lazy Dog.',
    'Sequential Models in Keras are Defined as a Sequence of Layers.',
    'You Need to Ensure The Input Layer Has The Right Number of Inputs.',
    'What Best For Evaluation Metrics is That You Decide The Optimum Number of Layers and The Parameters and Steps in Each Layer.',
    'A Heuristics Approach is Also Used.',
    'The Best Network Structure is Found Through a Process of Trial-and-Error experimentation.',
    'Generally, You Need a Network Large Enough to Capture The Structure of The Problem.',
    'Having Defined The Model in Terms of Layers, You Need to Declare The Loss Function, The Optimizer, and The Evaluation Metrics.',
    'When The Model is Proposed, The Initial Weight and Bias Values are Assumed to be 0 or 1, a Random Normally Distributed Number, or Any Other Convenient Numbers.',
    'The Journey From Initial Values to Optimal Values Needs a Motivation, Which Will Minimize The Cost Function/Lost Function.'
]

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")
model

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

SentenceTransformer(
  (0): Transformer({'transformer_task': 'feature-extraction', 'modality_config': {'text': {'method': 'forward', 'method_output_name': 'last_hidden_state'}}, 'module_output_name': 'token_embeddings', 'architecture': 'BertModel'})
  (1): Pooling({'embedding_dimension': 384, 'pooling_mode': 'mean', 'include_prompt': True})
  (2): Normalize({})
)

In [ ]:
embeddings = model.encode(
    sentences,
    convert_to_numpy=True
)

embeddings.shape

(12, 384)

In [ ]:
embeddings[0][:110]

array([-0.01195315, -0.05562935, -0.00824257,  0.00889046,  0.02768427,
        0.11398811,  0.0146988 , -0.0318959 ,  0.04145178, -0.08188555,
        0.01413271, -0.02033361,  0.04077511,  0.02262852, -0.04784385,
        0.07633466, -0.00329894,  0.04053929, -0.04151126, -0.09595738,
        0.00275886,  0.06117341,  0.05333673, -0.0446904 , -0.05076976,
        0.04299559, -0.05940743,  0.00790485,  0.10338719,  0.01843008,
        0.02685579, -0.02852802,  0.03100763,  0.07762937, -0.0013566 ,
        0.01041263, -0.01150964,  0.0383571 , -0.04920458, -0.01525103,
       -0.03559209, -0.00363358,  0.02812768,  0.03145439,  0.06721427,
       -0.03931508, -0.10906401, -0.01975164, -0.02292146,  0.04114951,
       -0.08468425, -0.05844709, -0.00620921,  0.02703554, -0.00866036,
        0.02391588, -0.01988747, -0.01934548,  0.02159742, -0.06250764,
       -0.05213042, -0.0500552 , -0.01291964,  0.0481705 ,  0.09681351,
        0.01135208,  0.00043806,  0.02927307, -0.05133164,  0.00806909,
       -0.08993871,  0.0084457 , -0.08349556, -0.01301006, -0.04386091,
        0.08196076, -0.00815732, -0.06575707,  0.1127347 , -0.01684349,
        0.01217879, -0.0030201 ,  0.04705351, -0.02032247,  0.08469543,
        0.02303506,  0.07535385, -0.02460301, -0.05997257,  0.01717734,
       -0.05202338, -0.11151729,  0.0818629 ,  0.03181605, -0.08708591,
        0.02361916, -0.0237372 , -0.01839187,  0.04637825,  0.03641907,
       -0.01961484,  0.00787911,  0.10479283, -0.05839049, -0.01317854,
       -0.03595706, -0.01648162, -0.0097606 , -0.03524808, -0.09957031],
      dtype=float32)

# **5. SBERT For Analyzing Semantic Textual Similarity (STS)**

In [ ]:
sentences = [
    'The Cat Sits Outside',
    'A man is Playing Guitar',
    'The New Movie is Awesome',
    'The Cat Plays in The Garden',
    'A Woman Watches TV',
    'The New Movie is So Great',
    'Do You Like Pizza?',
    'You Are right. Anyway, Thank You So Much For The Warm Conversation. See You Later!',
    'I Hope You All Had a Great Weekend',
    'I Can See You Have All Got Your School Equipment and Masks, Well Done',
    'I Hate Wearing a Mask, Miss. It is So Uncomfortable!',
    'I Understand, But it is Extremely Important That We Keep Ourselves and Others Safe',
    'Now, Open Your Book and Copy Today Date and Title Off The Board',
    'Miss, I Can Not See The Date Properly',
    'Pupil is A Part of Your Eye That is in Charge of How Much Light Goes Into Our Eye',
    'Better to Finish it Quickly. I Have to Submit The Report to The Manager'
]

embeddings = model.encode(
    sentences,
    convert_to_numpy=True
)
embeddings

array([[ 0.13919115,  0.00302902,  0.04701473, ...,  0.06407333,
        -0.01625155,  0.06362093],
       [ 0.02266129, -0.00138859, -0.00561351, ..., -0.02249004,
         0.08458396, -0.02826073],
       [-0.1004432 , -0.0773927 , -0.00137415, ..., -0.00104971,
         0.07181142,  0.02205477],
       ...,
       [ 0.03780555,  0.01295972,  0.06478752, ...,  0.07640478,
        -0.02517262,  0.01154895],
       [ 0.06587531, -0.03611827, -0.03740051, ...,  0.11304723,
         0.0143741 , -0.01582673],
       [ 0.02521353,  0.06769085, -0.02292574, ..., -0.00371493,
        -0.03869829,  0.05546784]], dtype=float32)

In [ ]:
def cosine_similarity(a,b):
  score = np.dot(a,b) / (norm(a) * norm(b))
  return score

In [ ]:
cosine_similarity(embeddings[0], embeddings[1])

np.float32(0.036330365)

In [ ]:
cosine_similarity(embeddings[3], embeddings[6])

np.float32(0.0899832)

In [ ]:
cosine_similarity(embeddings[5], embeddings[11])

np.float32(0.026413865)

In [ ]:
cosine_scores = util.cos_sim(embeddings, embeddings)
cosine_scores.shape

torch.Size([16, 16])

In [ ]:
pairs = []
for i in range(len(cosine_scores)-1):
  for j in range(i+1, len(cosine_scores)):
    pairs.append(
        {
            'index': [i,j],
            'score': cosine_scores[i][j]
        }
    )


len(pairs)

120

In [ ]:
pca = PCA(n_components=3)
embeddings_reduced = pca.fit_transform(embeddings)
embeddings_reduced

array([[-0.7126087 , -0.13850935,  0.11694185],
       [-0.3860705 , -0.01317526,  0.05827897],
       [ 0.07443842,  0.8253459 , -0.08412052],
       [-0.7984908 , -0.00400809,  0.121751  ],
       [-0.27861634, -0.2981685 , -0.11935136],
       [ 0.07202154,  0.8189547 , -0.09376029],
       [-0.04736597,  0.21521193,  0.27749327],
       [ 0.34761873, -0.19165985, -0.01712299],
       [ 0.29292098,  0.16257063,  0.10488606],
       [ 0.5031339 , -0.24274239,  0.17748699],
       [ 0.2827542 , -0.14595936,  0.45458087],
       [ 0.2508456 , -0.14664206,  0.28647158],
       [ 0.08846514, -0.15671292, -0.66000885],
       [ 0.0778795 , -0.29867452, -0.44929445],
       [ 0.11077157, -0.27864245,  0.3314599 ],
       [ 0.12230284, -0.10718893, -0.50569236]], dtype=float32)

In [ ]:
x, y = embeddings_reduced[:, 0], embeddings_reduced[:, 1]

# KMeans Clustering
n_clusters = min(5, len(sentences))
kmeans = KMeans(
    n_clusters=n_clusters,
    random_state=42,
    n_init='auto'
)
labels = kmeans.fit_predict(embeddings_reduced)
cluster_centers = kmeans.cluster_centers_

palette = [
    '#4C72B0', '#DD8452', '#55A868',
    '#C44E52', '#8172B2', '#937860',
    '#DA8BC3', '#8C8C8C', '#CCB974', '#64B5CD'
]

point_colors = [palette[l % len(palette)] for l in labels]

# KNN edges (intra-cluster only)
k = 3
nbrs = NearestNeighbors(
    n_neighbors= k + 1
).fit(embeddings_reduced)

_, indices = nbrs.kneighbors(embeddings_reduced)


edge_traces = []
for i, neighbors in enumerate(indices):
  for j in neighbors[1:]:
    if labels[i] == labels[j]:
      edge_traces.append(go.Scatter(
          x=[x[i],
             x[j]],
          y=[y[i],
             y[j]],
          mode='lines',
          line=dict(color=palette[labels[i] % len(palette)], width=1),
          opacity=0.25,
          hoverinfo='skip',
          showlegend=False
      ))

# KDE per cluster
contour_traces = []
for c in range(n_clusters):
  mask = labels == c
  if mask.sum() < 3:
    continue
  cx, cy = x[mask], y[mask]
  kde = gaussian_kde(np.vstack(
      [cx, cy]
  ), bw_method=0.4)
  xi, yi = np.mgrid[
      x.min(): x.max(): 60j,
      y.min(): y.max(): 60j
  ]

  zi = kde(np.vstack([xi.ravel(), yi.ravel()])).reshape(xi.shape)
  contour_traces.append(go.Contour(
      x=xi[:,0], y=yi[0], z=zi.T,
      colorscale=[
          [0,
           'rgba(0,0,0,0)'],
          [1, palette[c % len(palette)]]
      ],

      opacity=0.18,
      showscale=False,
      ncontours=5,
      contours_coloring='fill',
      hoverinfo='skip',
      showlegend=False
  ))


# cluster cebter labels
center_trace = go.Scatter(
    x=cluster_centers[:,0],
    y=cluster_centers[:, 1],
    mode='markers+text',
    text=[f'Cluster {i}' for i in range(n_clusters)],
    textposition='top center',
    textfont=dict(
        size=11,
        color='white',
        family='Arial Black'
    ),

    marker=dict(
        symbol='diamond',
        size=16,
        color=[palette[i % len(palette)] for i in range(n_clusters)],
        line=dict(color='white', width=2)
    ),

    hoverinfo='text',
    name='Cluster centers',
)


# points
point_trace = go.Scatter(
    x=x,
    y=y,
    mode='markers',
    marker=dict(
        size=11,
        color=point_colors,
        line=dict(color='white', width=1.2),
        opacity=0.9
    ),

    text=[
        f"<b>{s}</b><br>Cluster {labels[i]}"
        for i, s in enumerate(sentences)
    ],

    hovertemplate="%{text}<extra></extra>",
    name='Sentences'
)


# annotation labels (visible on hover via customdata trick)
label_trace = go.Scatter(
    x=x,
    y=y,
    mode='text',
    text=[f'  {s}' for s in sentences],
    textposition='middle right',
    textfont=dict(size=8, color="#333333"),
    hoverinfo='skip',
    showlegend=False,
    visible=True
)


# assemble
fig = go.Figure(
    data=[*contour_traces,
          *edge_traces,
          center_trace,
          point_trace,
          label_trace]
)

fig.update_layout(
    title=dict(
        text="<b>Sentence Embedding Space</b>",
        font=dict(size=17),
        x=0.5,
        xanchor='center'
    ),

    xaxis=dict(
        title='Component 1',
        showgrid=True,
        gridcolor="#ececec",
        zeroline=False,
        showline=True,
        linecolor="#cccccc"
    ),


    yaxis=dict(
        title='Component 2',
        showgrid=True,
        gridcolor='#ececec',
        zeroline=False,
        showline=True,
        linecolor='#cccccc'
    ),

    plot_bgcolor='white',
    paper_bgcolor='white',
    legend=dict(
        orientation='h',
        y=-0.13,
        bgcolor="rgba(255, 255, 255, 0.7)",
        bordercolor="#dddddd",
        borderwidth=1
    ),

    autosize=True,
    height=1300,
    margin=dict(l=60, r=60, t=80, b=70)
),

# togle labels button
updatemenus = [
    dict(
        type='buttons',
        direction='left',
        x=1.0,
        y=1.08,
        xanchor='right',
        buttons=[
            dict(label='Labels on',
                 method='update',
                 args=[
                     {
                         'visible': [True] * len(contour_traces) + [True] * len(edge_traces) + [True, True, True]
                     }
                 ]),

            dict(
                label='Label Off',
                method='Update',
                args=[
                    {
                        'visible': [True] * len(contour_traces) + [True] * len(edge_traces) + [True, True, False]
                    }
                ]
            )
        ],

        bgcolor='white',
        bordercolor="#cccccc",
        font=dict(size=11)
    )
]

fig.show()

# **6. Preparing The Datasets**

[DOWNLOAD DATASETS](https://www.kaggle.com/datasets/nandini1999/perfume-recommendation-dataset?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkGuidedProjectsIBMGPXX068IEN1371-2022-01-01)

In [ ]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "final_perfume_data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "nandini1999/perfume-recommendation-dataset",
  file_path,
  pandas_kwargs={'encoding':'unicode_escape'}
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

# print("First 5 records:", df.head())
df.head(7)

Using Colab cache for faster access to the 'perfume-recommendation-dataset' dataset.

,Name,Brand,Description,Notes,Image URL
0,Tihota Eau de Parfum,Indult,"Rapa Nui for sugar, Tihota is, quite simply, ...","Vanilla bean, musks",https://static.luckyscent.com/images/products/...
1,Sola Parfum,Di Ser,A tribute to the expanse of space extending f...,"Lavender, Yuzu, Lemongrass, Magnolia, Geraniu...",https://static.luckyscent.com/images/products/...
2,Kagiroi Parfum,Di Ser,An aromatic ode to the ancient beauty of Japa...,"Green yuzu, green shikuwasa, sansho seed, cor...",https://static.luckyscent.com/images/products/...
3,Velvet Fantasy Eau de Parfum,Montale,Velvet Fantasy is a solar fragrance where cit...,"tangerine, pink pepper, black coffee, leat...",https://static.luckyscent.com/images/products/...
4,A Blvd. Called Sunset Eau de Parfum,A Lab on Fire,There's no way A Lab On Fire could relocate t...,"Bergamot, almond, violet, jasmine, leather, s...",https://static.luckyscent.com/images/products/...
5,Freckled and Beautiful Eau de Parfum,A Lab on Fire,There's no beauty quite like being young in t...,"Orange flower, neroli, honeysuckle, warm milk...",https://static.luckyscent.com/images/products/...
6,Exit the King Eau de Parfum,Etat Libre d'Orange,"In these tumultuous times, a fragrance that c...","Timur JE, Soap Foam Accord (Aldehydes & Musk)...",https://static.luckyscent.com/images/products/...

In [ ]:
list(df.Notes[0:21])

[' Vanilla bean, musks',
 ' Lavender, Yuzu, Lemongrass, Magnolia, Geranium, Jasmine, Frankincense, Myrrh',
 ' Green yuzu, green shikuwasa, sansho seed, coriander, ylang-ylang, shiso, rosewood, vetiver, hinoki, cypriol, patchouli, agarwood',
 ' tangerine,  pink pepper,  black coffee,  leather,  violet,  jasmine,  lily of the valley,  heliotrope powder,  vanilla,  amber, sandalwood,  toffee,  musk,  oakmoss',
 ' Bergamot, almond, violet, jasmine, leather, sandalwood, vanilla, tonka',
 ' Orange flower, neroli, honeysuckle, warm milk, pastry, salicylates, sandalwood, vanilla bean, heliotrope',
 ' Timur JE, Soap Foam Accord (Aldehydes & Musk), Pink Pepper, Jasmine e-pure, Rose Superessence, Lily-of-the-valley Accord, Patchouli, Moss Absolute, Sandalwood Accord & Orcanox',
 ' Tobacco, hay, elemi, copaiba, olibanum, nutmeg, black pepper, castoreum, atlas cedar, oakmoss, cognac, ambroxan, norlimbanol, cinnamon, cumin seed, ash',
 ' Saffron, champaca, fir balsam, beeswax, amber, damask rose, rose de mai, tobacco, leather, dark chocolate, prune, oud, musk, oakmoss, ambrette, smoke, incense, ylang ylang',
 ' Cambodian oud, Trat oud, jasmin sambac, champaca, olibanum, turmeric, clove, caraway, cardamom, cinnamon, cumin, coriander, gardenia, opoponax, saffron, sandalwood, patchouli, musk',
 ' Violet, champaca, rosewood, beeswax, frankincense, myrrh, coffee bean, rose, tobacco, hay, jasmine, leather, castoreum, hyrax, civet, musk, oud, turmeric, cumin',
 ' Cinnamon, ginger, black pepper, cardamom, cassia, cumin, turmeric, caraway, nutmeg, clove, saffron, hay, kaffir lime, oud, galbanum, ghee butter, jasmine, champaca, tuberose, beeswax, incense, myrrh, spikenard, costus, benzoin, ash, goat hair tincture, oud, mushroom, civet, hyrax',
 ' Eucalyptus, menthol honey gumdrops, mimosa, black tea, geranium, incense, spices, vetiver, musk, amber, oakmoss, vanilla, sandalwood',
 ' Grapefruit, Damascene rose, amber woods accord, sage, Centifolia rose, labdanum',
 ' Rose, shiso, guaiac',
 ' Tuberose, White Rose Petals, Pomelo, Sandalwood, Coconut Milk, Musk',
 ' Bergamot, pink pepper, raspberry, rose, red satin lipstick, tuberose, cardamom, iris, cocoa, sandalwood, amber',
 'ocean, apricot, almond, fresh dairy, aromatic herbs, spices',
 'black rose, ash, champagne',
 ' Absolute of Ylang Ylang, Absolute of Champaca, Vanilla of Tahiti CO2, Amber, Sandalwood, Musk',
 ' Fig, Black tea, Cardamom essence, Absolute of iris, Bourbon, vetiver, Sandalwood from India, Absolute of Tonka bean']

In [ ]:
df.rename(
    columns={"ï»¿Name": "Name"}, inplace=True
)
df['Name'] = df['Brand'] + " - " + df['Name']
df.drop(
    labels=['Description',
            'Image URL',
            'Brand'], axis=1, inplace=True
)

df.head(8)

,Name,Notes
0,Indult - Tihota Eau de Parfum,"Vanilla bean, musks"
1,Di Ser - Sola Parfum,"Lavender, Yuzu, Lemongrass, Magnolia, Geraniu..."
2,Di Ser - Kagiroi Parfum,"Green yuzu, green shikuwasa, sansho seed, cor..."
3,Montale - Velvet Fantasy Eau de Parfum,"tangerine, pink pepper, black coffee, leat..."
4,A Lab on Fire - A Blvd. Called Sunset Eau de P...,"Bergamot, almond, violet, jasmine, leather, s..."
5,A Lab on Fire - Freckled and Beautiful Eau de ...,"Orange flower, neroli, honeysuckle, warm milk..."
6,Etat Libre d'Orange - Exit the King Eau de Parfum,"Timur JE, Soap Foam Accord (Aldehydes & Musk)..."
7,PRIN - Eshu Extrait,"Tobacco, hay, elemi, copaiba, olibanum, nutme..."

In [ ]:
df.Notes.isnull().sum()

np.int64(80)

In [ ]:
df.dropna(inplace=True)
df.reset_index(
    inplace=True,
    drop=True
)

df.shape

(2111, 2)

In [ ]:
words = [
    'Perfume Oil',
    'Extrait',
    'Travel',
    'Hair',
    'Body',
    'Hand',
    'Intense',
    'Intensivo',
    'Oil'
]

index_to_drop = []
for index, name in enumerate(df.Name):
  if any(word.lower() in name.lower() for word in words):
    index_to_drop.append(index)

In [ ]:
df.drop(index_to_drop, axis=0, inplace=True)
df.reset_index(inplace=True, drop=True)
df.shape

(1612, 2)

# **7. Creating Perfume Notes Embeddings.**

In [ ]:
df.Notes = df.Notes.apply(lambda x: str(x))
notes = df.Notes.to_list()
len(notes)

1612

In [ ]:
model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

note_embeddings = model.encode(
    notes,
    show_progress_bar=True,
    batch_size=64
)

note_embeddings

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/26 [00:00<?, ?it/s]

array([[-0.0092152 , -0.00588338,  0.07965599, ..., -0.0465106 ,
         0.06299062, -0.04927407],
       [-0.02047073, -0.05532719,  0.08350064, ...,  0.01296031,
         0.07795755,  0.02532452],
       [ 0.02241134, -0.04566668, -0.01234638, ..., -0.04174406,
         0.03946609,  0.11506725],
       ...,
       [-0.03481103, -0.02457182,  0.06051833, ..., -0.07823157,
         0.07495947, -0.01130766],
       [-0.01330567, -0.08048292,  0.09501222, ..., -0.01180693,
         0.06006651, -0.01370788],
       [ 0.02489633, -0.05313787,  0.07445267, ..., -0.04210577,
         0.00254264, -0.01733846]], dtype=float32)

In [ ]:
print(note_embeddings.shape)
print('\n')
print(note_embeddings[0][:1000])

(1612, 384)


[-9.21519939e-03 -5.88337751e-03  7.96559900e-02  1.10818418e-02
  9.20339227e-02 -6.11888319e-02  6.98084012e-02  4.19339053e-02
  1.31228715e-02 -1.08811317e-03  6.51104450e-02 -8.00822377e-02
  1.98498443e-02 -1.38294548e-01 -2.25123726e-02 -7.48573989e-03
  1.24105453e-01  6.44884557e-02  6.84045488e-03 -1.72451567e-02
  4.11716215e-02  1.70634519e-02  8.54872726e-03  6.71903193e-02
 -5.61139658e-02  1.93254333e-02  2.49864291e-02 -2.41799150e-02
 -3.02803852e-02 -1.20585941e-01 -1.73769165e-02  3.18373106e-02
  1.31492205e-02  2.14791838e-02 -1.02081552e-01  3.20526101e-02
 -1.53568741e-02 -2.60394718e-02  6.54244274e-02 -1.51386177e-02
  1.59238949e-02 -6.78843930e-02  1.50188711e-02 -1.73686482e-02
 -6.78988323e-02 -1.90712158e-02  1.83811057e-02 -5.66424839e-02
 -1.30136847e-03 -1.89556982e-02 -1.62308179e-02 -6.89333677e-02
 -3.58953071e-03  2.25383975e-02  1.79827586e-02 -5.44826835e-02
 -1.45096451e-01  9.61968675e-03  4.90830876e-02  6.90806583e-02
 -1.80102792e-02 -3.63226496e-02  3.77785563e-02  4.92834076e-02
  3.09103988e-02 -2.89589893e-02 -6.00081608e-02  5.27622784e-03
 -1.52251665e-02 -3.53126526e-02 -4.20313552e-02  3.07366457e-02
  1.49633002e-03 -1.67366005e-02 -1.12933122e-01  1.22829966e-01
  3.00944783e-02 -4.83127031e-03 -1.68482289e-02 -2.88763251e-02
 -6.69324771e-02  2.42313500e-02 -1.85596087e-04 -6.01481870e-02
 -3.54192825e-03  5.05954511e-02 -2.88541079e-03  4.86909710e-02
 -3.74186821e-02  1.77205838e-02  1.73577461e-02  3.56207378e-02
  4.84572016e-02  8.51871371e-02 -4.21870276e-02  2.10288260e-02
  2.52769850e-02 -3.19696665e-02 -5.39943986e-02  1.00559056e-01
 -2.49814354e-02  3.14568914e-02  3.90691385e-02 -5.94356544e-02
 -1.55998478e-02 -7.04329684e-02 -8.47721398e-02 -6.53179213e-02
  3.87326404e-02  1.04637658e-02 -1.74919391e-04 -2.39475183e-02
 -9.42876339e-02  4.44852002e-02 -5.45734772e-04 -1.43164396e-01
  4.23295386e-02 -4.86213900e-02  2.25564223e-02 -4.47526909e-02
  8.92055221e-03 -3.91242839e-03 -3.73247452e-02 -2.22096164e-02
 -8.79957378e-02 -6.12023659e-02 -3.31960246e-03 -7.68011071e-34
 -4.51207310e-02 -3.36557813e-02 -5.36098611e-03  6.76754490e-02
  6.03817217e-03  2.40844525e-02 -5.73407561e-02 -2.36281920e-02
 -3.36366631e-02 -2.12315898e-02 -6.88778087e-02  3.34556215e-02
 -1.20753624e-01  2.87262648e-02  3.55798155e-02 -3.56603824e-02
 -1.38712786e-02 -9.58522968e-03  4.27177809e-02 -3.65748033e-02
 -1.06978975e-01  7.74317235e-02 -8.17401614e-03  4.00844179e-02
 -1.36498678e-02 -2.81760134e-02  1.17370496e-02 -1.36615321e-01
 -9.20808781e-03  5.29398909e-03  3.61876711e-02  5.80267981e-03
  4.92300466e-02  7.66136274e-02 -6.12276085e-02 -6.25596289e-03
  4.31007007e-03 -1.47482865e-02 -4.75778133e-02 -2.54115555e-03
 -3.41047235e-02 -1.90590248e-02 -1.24392658e-02 -7.52721215e-03
 -4.20763902e-03  8.81067738e-02  5.48555031e-02  4.72605340e-02
  7.67756253e-03  3.02100871e-02 -4.76060886e-05  1.91028938e-02
  8.16338733e-02 -1.43886404e-03  1.59422401e-02 -2.48467475e-02
  9.97051224e-03  1.17642507e-02 -3.13194133e-02  4.39658798e-02
 -3.12354174e-02  5.69702722e-02  2.14990620e-02 -6.42381459e-02
 -4.76153307e-02 -1.29928645e-02 -1.34544969e-01 -7.44456239e-03
  4.82446924e-02  8.31539705e-02  4.19500619e-02  7.50944344e-03
 -1.73761752e-02  3.87647338e-02 -1.16277887e-02 -6.52288795e-02
 -5.36968140e-03  2.56948378e-02 -4.91245762e-02  8.99671912e-02
  1.05060793e-01  4.52481322e-02 -3.09450999e-02  1.62863024e-02
  1.79336257e-02  8.47342983e-02 -6.95445165e-02 -2.18952280e-02
  8.87990221e-02  6.24734238e-02 -9.41420272e-02 -1.38979284e-02
 -1.91174671e-02  1.58410538e-02 -9.13927257e-02  8.42309752e-34
  4.84155975e-02 -2.14464292e-02  3.96594070e-02  1.84645429e-01
  3.34947556e-02  3.72646190e-02 -3.15622240e-03 -1.54227950e-02
 -2.80390736e-02  1.19806000e-03 -6.64877333e-03 -2.01235479e-03
  5.56396060e-02 -1.38779934e-02  7.34023824e-02  8.53985101e-02
  4.63077500e-02  3.99668403e-02 -2.13102102e-02 -9.96509008e-03
 -7.03655481e-02  8.37581158e-02 -7.03509077e-02  3.53585333e-02
 -2.97122262e-02  5.76748736e-02 -2.01904364e-02  8.67071822e-02
 -8.59427750e-02 -6.65488616e-02 -1.24436608e-02 -5.22740260e-02
  3.55451778e-02 -8.10210686e-03  1.52103510e-02 -5.05941026e-02
 -3.55550237e-02  7.05819130e-02  1.98923461e-02  7.97044300e-03
 -4.75213043e-02 -1.06155686e-02  9.70757380e-03  4.21532504e-02
 -4.84704636e-02 -3.31026316e-02 -2.84255785e-03 -2.69024801e-02
  3.59094627e-02  7.56813809e-02 -1.46810897e-03 -7.75090000e-03
 -4.66572344e-02 -2.98244320e-02 -6.45415531e-03 -2.03897581e-02
 -9.94567275e-02  3.13112140e-02  5.69617078e-02 -7.49362633e-03
  8.12239479e-03  5.80354081e-03 -6.37071393e-03  1.54592562e-03
  7.39949429e-03  4.67502326e-02 -9.11435392e-03 -3.02847885e-02
 -2.47249771e-02 -1.38006331e-02  1.00585021e-01 -1.59452613e-02
 -4.42912169e-02 -6.82744160e-02  8.93283635e-02 -1.15649216e-02
 -9.05337185e-03  2.90885102e-03  3.63099552e-03 -4.45539579e-02
 -1.93984956e-02  4.91997562e-02 -1.51414692e-03  2.66040508e-02
  6.67515621e-02  9.76988375e-02  2.14664475e-03 -3.85777769e-03
  8.35947394e-02  2.81771068e-02  2.92856917e-02  6.70235157e-02
 -7.32285203e-03  6.48507103e-02  7.50335082e-02 -1.49346562e-08
 -1.84711756e-03  4.11713045e-05 -3.93220522e-02  7.98601508e-02
  7.29373917e-02  3.90798487e-02  2.26967726e-02  2.33405903e-02
 -2.71458067e-02  4.40164283e-02 -4.37145717e-02  3.03930081e-02
  5.81429712e-03  1.04086898e-01  7.17304796e-02  5.54497994e-04
  5.24786999e-03  2.89221797e-02 -2.77595557e-02  2.45546885e-02
 -5.58876842e-02  1.60314199e-02  4.02129889e-02  5.50427027e-02
 -1.84727777e-02 -2.66077537e-02  7.47633632e-03 -1.64930355e-02
  1.56112641e-01  8.41431692e-02  3.01193213e-03  4.47113439e-02
 -2.50715073e-02 -6.34726807e-02 -5.75261749e-02 -1.55207608e-02
 -8.56468379e-02  1.80013962e-02 -2.44256146e-02 -2.82252356e-02
 -2.61645131e-02 -3.52585837e-02  1.04466408e-01 -3.35992016e-02
 -1.29648611e-01 -3.43741514e-02 -6.34987876e-02  3.36840898e-02
 -3.70527096e-02  8.61560777e-02  1.66918002e-02  5.41227162e-02
 -5.94140543e-03  6.63366094e-02 -3.87566746e-03 -1.45675525e-01
  1.05424054e-01 -8.56659096e-03 -6.43593669e-02 -4.08769250e-02
 -6.28144620e-03 -4.65105996e-02  6.29906207e-02 -4.92740721e-02]

# **8. Recommending Perfumes Using Cosine Similarity**

In [ ]:
cosine_scores = util.cos_sim(
    note_embeddings,
    note_embeddings
)

cosine_scores.shape

torch.Size([1612, 1612])

In [ ]:
pairs = []

for i in range(len(cosine_scores)-1):
  for j in range(i+1, len(cosine_scores)):
    pairs.append(
        {
            'index': [i,j],
            'score': cosine_scores[i][j]
        }
    )

len(pairs)

1298466

In [ ]:
sorted_pairs = sorted(
    pairs,
    key=lambda x: x['score'],
    reverse=True
)

for pair in sorted_pairs[0:20]:
  i, j = pair['index']
  print(f"{df.iloc[i, 0]} | {df.iloc[j,0]} \n Score: {pair['score']:.3f} \n")

Carthusia - Fiori di Capri Parfum | Carthusia - Fiori di Capri Eau de Parfum
 Score: 1.000

Comme des Garcons - 2 Candle | Comme des Garcons - 2 Eau de Parfum
 Score: 1.000

Carthusia - Mediterraneo Parfum | Carthusia - Mediterraneo Eau de Parfum
 Score: 1.000

Juliette Has a Gun - Not A Perfume Superdose Eau de Parfum | Juliette Has a Gun - Not a Perfume Eau de Parfum
 Score: 1.000

Maison Francis Kurkdjian - Gentle fluidity Silver Eau de Parfum | Maison Francis Kurkdjian - gentle Fluidity Gold Eau de Parfum
 Score: 1.000

Roja Parfums - Elysium Parfum Cologne | Roja Parfums - Vetiver Parfum Cologne
 Score: 1.000

Ormonde Jayne - Ormonde Elixir Parfum | Ormonde Jayne - Ormonde Woman Eau de Parfum
 Score: 0.984

PARFUMS DE NICOLAI - Incense Oud Eau de Parfum | PARFUMS DE NICOLAI - Oud Sublime Elixir de Parfum
 Score: 0.969

Ormonde Jayne - Ta'if Elixir Parfum | Ormonde Jayne - Ta'if Eau de Parfum
 Score: 0.960

J-Scent - Hisui (Jade) Eau de Parfum | J-Scent - Shaft of Light Eau de Parfum
 Score: 0.946

Roja Parfums - Danger Parfum Cologne | Roja Parfums - Scandal Parfum Cologne
 Score: 0.943

Xerjoff - Oud Stars - Alexandria III Parfum | Xerjoff - Oud Stars - Alexandria II Eau de Parfum
 Score: 0.943

Charenton Macerations - Asphalt Rainbow Scratch & Sniff Sticker Set | Charenton Macerations - Asphalt Rainbow Eau de Parfum
 Score: 0.942

Ormonde Jayne - Royal Elixir Parfum | Ormonde Jayne - Ambre Royal Eau de Parfum
 Score: 0.938

Les Bains Guerbois - Eau de Cologne | Les Bains Guerbois - 2015 Le Phenix Eau de Parfum
 Score: 0.934

Amouage - Lyric for Women Eau de Parfum | Amouage - Lyric for Men Eau de Parfum
 Score: 0.929

The House Of Oud - Golden Powder Eau de Parfum | Xerjoff - Casamorati - Bouquet Ideale Eau de Parfum
 Score: 0.925

Costamor - Beachwood Eau de Parfum | ANFAS - Salam Eau de Parfum
 Score: 0.922

Montale - Oud Dream Eau de Parfum | Parfums MDCI - Fetes Persanes Eau de Parfum
 Score: 0.920

19-69 - Villa Nellcote Eau de Parfum | J-Scent - Shaft of Light Eau de Parfum
 Score: 0.918

# **9. Getting Your Own Perfume Suggestions.**

In [ ]:
my_perfumes = pd.DataFrame(
    [
        [
            'Jo Malone - English Pear & Freesia',
            'Pear, Melon, Freesia, Rose, Musk, Patchouli, Rhuburb, Amber'
        ],

        [
            'Jo Malone - Myrrh & Tonka',
            'Lavender, Myrrh, Tonka Bean, Vanilla, Almond'
        ],

        [
            'Jo Malone - Oud & Bergamot',
            'orange, bergamot, lemon, cedar and oud.'
        ],

        [
            'Guerlain - Néroli Outrenoir',
            'Petitgrain, Bergamot, Tangerine, Lemon, Grapefruit, Tea, Neroli, Orange Blossom, Smoke, Earthy Notes, Vanilla, Benzoin, Ambrette, Oakmoss'
        ],

        [
            'Guerlain - Épices Volées',
            'Coriander, Lemon, Artemisia, Bergamot, Clove, Cardamom, Sage, Bulgarian Rose, Sandalwood, Patchouli, Benzoin, Labdanum.'
        ],

        [
            'Guerlain - Aqua Allegoria Nerolia Vetiver Eau de Toilette',
            'Basil, Vetiver, Fig Accord, Neroli'
        ],

        [
            'Chloe Eau de Parfum',
            'Peony, Litchi, Freesia, Rose, Lily-of-the-valley, Magnolia, Virginia Cedar, Amber.'
        ]
    ],
    columns=df.columns
)


my_perfumes

,Name,Notes
0,Jo Malone - English Pear & Freesia,"Pear, Melon, Freesia, Rose, Musk, Patchouli, R..."
1,Jo Malone - Myrrh & Tonka,"Lavender, Myrrh, Tonka Bean, Vanilla, Almond"
2,Jo Malone - Oud & Bergamot,"orange, bergamot, lemon, cedar and oud."
3,Guerlain - Néroli Outrenoir,"Petitgrain, Bergamot, Tangerine, Lemon, Grapef..."
4,Guerlain - Épices Volées,"Coriander, Lemon, Artemisia, Bergamot, Clove, ..."
5,Guerlain - Aqua Allegoria Nerolia Vetiver Eau ...,"Basil, Vetiver, Fig Accord, Neroli"
6,Chloe Eau de Parfum,"Peony, Litchi, Freesia, Rose, Lily-of-the-vall..."

# **10. Create Perfume Embeddings**

In [ ]:
notes = list(my_perfumes.Notes)

model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

my_embeddings = model.encode(
    notes,
    show_progress_bar=True
)
my_embeddings

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Batches:   0%|          | 0/1 [00:00<?, ?it/s]

array([[ 0.00647851, -0.005287  ,  0.02603362, ..., -0.0057166 ,
         0.07681699,  0.05532723],
       [ 0.00634501, -0.0931145 ,  0.04959133, ..., -0.01040181,
         0.03165305, -0.04884854],
       [-0.04282153,  0.02124743, -0.01599683, ..., -0.03531112,
         0.01644192,  0.02172926],
       ...,
       [-0.01359168, -0.03799743, -0.01397787, ...,  0.01430065,
         0.07208499,  0.08501904],
       [ 0.00803824,  0.00309042,  0.00879411, ..., -0.05991153,
         0.06843214,  0.01933537],
       [-0.01549409,  0.00785855,  0.07611383, ...,  0.01109195,
         0.01923159,  0.02546484]], dtype=float32)

# **11. Produce Cosine Similarity Scores:**

In [ ]:
cosine_scores = util.cos_sim(
    my_embeddings,
    note_embeddings
)

cosine_scores

tensor([[0.4117, 0.5761, 0.6299,  ..., 0.5459, 0.6969, 0.5783],
        [0.5386, 0.7265, 0.5441,  ..., 0.4743, 0.7082, 0.6617],
        [0.2268, 0.5580, 0.5189,  ..., 0.4391, 0.6535, 0.5439],
        ...,
        [0.1975, 0.7170, 0.6387,  ..., 0.4639, 0.6641, 0.6336],
        [0.2132, 0.4485, 0.5167,  ..., 0.3229, 0.3993, 0.3617],
        [0.2359, 0.6094, 0.6097,  ..., 0.5107, 0.6346, 0.5316]])

# **12. Sort The Perfume Similarity Scores**

In [ ]:
my_pairs = []

for i in range(cosine_scores.shape[0]):
  for j in range(cosine_scores.shape[1]):
    my_pairs.append(
        {
            'index': [i,j],
            'score': cosine_scores[i][j]
        }
    )

my_sorted_pairs = sorted(
    my_pairs,
    key=lambda x: x['score'],
    reverse=True
)

my_sorted_pairs

[{'index': [1, 1528], 'score': tensor(0.8580)},
 {'index': [4, 1459], 'score': tensor(0.8565)},
 {'index': [3, 503], 'score': tensor(0.8544)},
 {'index': [3, 530], 'score': tensor(0.8522)},
 {'index': [2, 1345], 'score': tensor(0.8512)},
 {'index': [3, 1075], 'score': tensor(0.8501)},
 {'index': [3, 959], 'score': tensor(0.8482)},
 {'index': [3, 137], 'score': tensor(0.8462)},
 {'index': [3, 692], 'score': tensor(0.8454)},
 {'index': [4, 415], 'score': tensor(0.8450)},
 {'index': [3, 1447], 'score': tensor(0.8407)},
 {'index': [3, 979], 'score': tensor(0.8400)},
 {'index': [4, 1046], 'score': tensor(0.8389)},
 {'index': [3, 445], 'score': tensor(0.8384)},
 {'index': [3, 415], 'score': tensor(0.8382)},
 {'index': [1, 1440], 'score': tensor(0.8353)},
 {'index': [3, 664], 'score': tensor(0.8336)},
 {'index': [4, 1262], 'score': tensor(0.8330)},
 {'index': [1, 1118], 'score': tensor(0.8312)},
 {'index': [3, 574], 'score': tensor(0.8309)},
 {'index': [4, 150], 'score': tensor(0.8307)},
 {'index': [3, 817], 'score': tensor(0.8305)},
 {'index': [4, 706], 'score': tensor(0.8290)},
 {'index': [4, 153], 'score': tensor(0.8289)},
 {'index': [3, 1047], 'score': tensor(0.8288)},
 {'index': [3, 202], 'score': tensor(0.8284)},
 {'index': [1, 1239], 'score': tensor(0.8277)},
 {'index': [4, 1420], 'score': tensor(0.8265)},
 {'index': [3, 330], 'score': tensor(0.8234)},
 {'index': [4, 157], 'score': tensor(0.8221)},
 {'index': [3, 1046], 'score': tensor(0.8201)},
 {'index': [4, 970], 'score': tensor(0.8198)},
 {'index': [4, 1515], 'score': tensor(0.8193)},
 {'index': [3, 301], 'score': tensor(0.8183)},
 {'index': [3, 1459], 'score': tensor(0.8181)},
 {'index': [4, 1431], 'score': tensor(0.8165)},
 {'index': [4, 787], 'score': tensor(0.8165)},
 {'index': [3, 976], 'score': tensor(0.8162)},
 {'index': [4, 1537], 'score': tensor(0.8158)},
 {'index': [4, 558], 'score': tensor(0.8152)},
 {'index': [4, 858], 'score': tensor(0.8142)},
 {'index': [3, 1170], 'score': tensor(0.8137)},
 {'index': [3, 1315], 'score': tensor(0.8128)},
 {'index': [3, 1457], 'score': tensor(0.8121)},
 {'index': [4, 674], 'score': tensor(0.8120)},
 {'index': [3, 1363], 'score': tensor(0.8110)},
 {'index': [3, 748], 'score': tensor(0.8107)},
 {'index': [4, 417], 'score': tensor(0.8105)},
 {'index': [3, 706], 'score': tensor(0.8103)},
 {'index': [3, 555], 'score': tensor(0.8096)},
 {'index': [4, 959], 'score': tensor(0.8095)},
 {'index': [4, 342], 'score': tensor(0.8086)},
 {'index': [3, 309], 'score': tensor(0.8084)},
 {'index': [3, 914], 'score': tensor(0.8071)},
 {'index': [4, 81], 'score': tensor(0.8069)},
 {'index': [3, 877], 'score': tensor(0.8066)},
 {'index': [4, 212], 'score': tensor(0.8061)},
 {'index': [4, 393], 'score': tensor(0.8048)},
 {'index': [4, 1016], 'score': tensor(0.8048)},
 {'index': [3, 489], 'score': tensor(0.8047)},
 {'index': [3, 476], 'score': tensor(0.8044)},
 {'index': [1, 258], 'score': tensor(0.8043)},
 {'index': [3, 1266], 'score': tensor(0.8037)},
 {'index': [4, 1546], 'score': tensor(0.8032)},
 {'index': [1, 629], 'score': tensor(0.8031)},
 {'index': [3, 465], 'score': tensor(0.8030)},
 {'index': [4, 323], 'score': tensor(0.8027)},
 {'index': [4, 301], 'score': tensor(0.8027)},
 {'index': [3, 98], 'score': tensor(0.8023)},
 {'index': [4, 1500], 'score': tensor(0.8022)},
 {'index': [4, 345], 'score': tensor(0.8019)},
 {'index': [3, 804], 'score': tensor(0.8013)},
 {'index': [4, 156], 'score': tensor(0.8012)},
 {'index': [0, 164], 'score': tensor(0.8007)},
 {'index': [4, 514], 'score': tensor(0.8003)},
 {'index': [3, 378], 'score': tensor(0.8000)},
 {'index': [4, 215], 'score': tensor(0.7998)},
 {'index': [4, 758], 'score': tensor(0.7993)},
 {'index': [3, 230], 'score': tensor(0.7990)},
 {'index': [1, 1268], 'score': tensor(0.7989)},
 {'index': [3, 1543], 'score': tensor(0.7988)},
 {'index': [4, 600], 'score': tensor(0.7988)},
 {'index': [3, 299], 'score': tensor(0.7987)},
 {'index': [4, 1266], 'score': tensor(0.7986)},
 {'index': [3, 81], 'score': tensor(0.7984)},
 {'index': [1, 815], 'score': tensor(0.7982)},
 {'index': [4, 976], 'score': tensor(0.7982)},
 {'index': [1, 1388], 'score': tensor(0.7981)},
 {'index': [4, 975], 'score': tensor(0.7981)},
 {'index': [3, 1118], 'score': tensor(0.7981)},
 {'index': [4, 800], 'score': tensor(0.7981)},
 {'index': [3, 1544], 'score': tensor(0.7976)},
 {'index': [3, 1513], 'score': tensor(0.7971)},
 {'index': [3, 1043], 'score': tensor(0.7962)},
 {'index': [4, 1356], 'score': tensor(0.7961)},
 {'index': [3, 481], 'score': tensor(0.7960)},
 {'index': [4, 1364], 'score': tensor(0.7952)},
 {'index': [4, 1400], 'score': tensor(0.7948)},
 {'index': [3, 619], 'score': tensor(0.7948)},
 {'index': [3, 1089], 'score': tensor(0.7946)},
 {'index': [3, 1132], 'score': tensor(0.7944)},
 {'index': [3, 157], 'score': tensor(0.7944)},
 {'index': [4, 1112], 'score': tensor(0.7943)},
 {'index': [1, 1523], 'score': tensor(0.7941)},
 {'index': [4, 815], 'score': tensor(0.7940)},
 {'index': [4, 1171], 'score': tensor(0.7940)},
 {'index': [4, 979], 'score': tensor(0.7936)},
 {'index': [3, 902], 'score': tensor(0.7935)},
 {'index': [1, 197], 'score': tensor(0.7935)},
 {'index': [4, 1127], 'score': tensor(0.7927)},
 {'index': [1, 903], 'score': tensor(0.7927)},
 {'index': [4, 319], 'score': tensor(0.7924)},
 {'index': [3, 1485], 'score': tensor(0.7922)},
 {'index': [4, 1360], 'score': tensor(0.7915)},
 {'index': [3, 332], 'score': tensor(0.7914)},
 {'index': [3, 1366], 'score': tensor(0.7911)},
 {'index': [3, 139], 'score': tensor(0.7910)},
 {'index': [3, 416], 'score': tensor(0.7908)},
 {'index': [3, 412], 'score': tensor(0.7906)},
 {'index': [4, 440], 'score': tensor(0.7901)},
 {'index': [3, 1393], 'score': tensor(0.7901)},
 {'index': [3, 648], 'score': tensor(0.7894)},
 {'index': [3, 135], 'score': tensor(0.7894)},
 {'index': [3, 556], 'score': tensor(0.7885)},
 {'index': [1, 684], 'score': tensor(0.7884)},
 {'index': [3, 120], 'score': tensor(0.7883)},
 {'index': [0, 1050], 'score': tensor(0.7883)},
 {'index': [3, 718], 'score': tensor(0.7881)},
 {'index': [3, 328], 'score': tensor(0.7881)},
 {'index': [4, 1248], 'score': tensor(0.7880)},
 {'index': [3, 1110], 'score': tensor(0.7879)},
 {'index': [0, 45], 'score': tensor(0.7877)},
 {'index': [0, 1303], 'score': tensor(0.7876)},
 {'index': [3, 385], 'score': tensor(0.7875)},
 {'index': [3, 596], 'score': tensor(0.7872)},
 {'index': [3, 843], 'score': tensor(0.7870)},
 {'index': [4, 1084], 'score': tensor(0.7870)},
 {'index': [3, 417], 'score': tensor(0.7869)},
 {'index': [4, 574], 'score': tensor(0.7868)},
 {'index': [4, 1378], 'score': tensor(0.7866)},
 {'index': [4, 1024], 'score': tensor(0.7866)},
 {'index': [1, 1592], 'score': tensor(0.7865)},
 {'index': [4, 139], 'score': tensor(0.7864)},
 {'index': [4, 914], 'score': tensor(0.7863)},
 {'index': [3, 573], 'score': tensor(0.7862)},
 {'index': [4, 1009], 'score': tensor(0.7860)},
 {'index': [1, 1106], 'score': tensor(0.7859)},
 {'index': [4, 931], 'score': tensor(0.7857)},
 {'index': [3, 1362], 'score': tensor(0.7854)},
 {'index': [4, 598], 'score': tensor(0.7853)},
 {'index': [3, 1016], 'score': tensor(0.7848)},
 {'index': [3, 627], 'score': tensor(0.7846)},
 {'index': [4, 98], 'score': tensor(0.7845)},
 {'index': [3, 1431], 'score': tensor(0.7840)},
 {'index': [4, 1185], 'score': tensor(0.7840)},
 {'index': [4, 172], 'score': tensor(0.7833)},
 {'index': [0, 646], 'score': tensor(0.7831)},
 {'index': [1, 4], 'score': tensor(0.7830)},
 {'index': [3, 1402], 'score': tensor(0.7829)},
 {'index': [1, 1524], 'score': tensor(0.7829)},
 {'index': [4, 695], 'score': tensor(0.7829)},
 {'index': [3, 1009], 'score': tensor(0.7820)},
 {'index': [3, 769], 'score': tensor(0.7819)},
 {'index': [4, 218], 'score': tensor(0.7813)},
 {'index': [3, 131], 'score': tensor(0.7811)},
 {'index': [4, 817], 'score': tensor(0.7811)},
 {'index': [4, 670], 'score': tensor(0.7804)},
 {'index': [3, 1463], 'score': tensor(0.7804)},
 {'index': [3, 345], 'score': tensor(0.7804)},
 {'index': [4, 1403], 'score': tensor(0.7802)},
 {'index': [3, 413], 'score': tensor(0.7801)},
 {'index': [4, 816], 'score': tensor(0.7798)},
 {'index': [4, 831], 'score': tensor(0.7798)},
 {'index': [4, 1123], 'score': tensor(0.7796)},
 {'index': [3, 227], 'score': tensor(0.7792)},
 {'index': [3, 1332], 'score': tensor(0.7786)},
 {'index': [3, 64], 'score': tensor(0.7785)},
 {'index': [0, 1125], 'score': tensor(0.7784)},
 {'index': [4, 371], 'score': tensor(0.7783)},
 {'index': [4, 147], 'score': tensor(0.7782)},
 {'index': [3, 605], 'score': tensor(0.7779)},
 {'index': [3, 1064], 'score': tensor(0.7779)},
 {'index': [3, 805], 'score': tensor(0.7777)},
 {'index': [3, 1085], 'score': tensor(0.7775)},
 {'index': [3, 1336], 'score': tensor(0.7774)},
 {'index': [4, 131], 'score': tensor(0.7773)},
 {'index': [4, 1382], 'score': tensor(0.7772)},
 {'index': [4, 1332], 'score': tensor(0.7771)},
 {'index': [4, 1000], 'score': tensor(0.7771)},
 {'index': [0, 768], 'score': tensor(0.7771)},
 {'index': [4, 414], 'score': tensor(0.7764)},
 {'index': [4, 418], 'score': tensor(0.7764)},
 {'index': [3, 272], 'score': tensor(0.7759)},
 {'index': [4, 745], 'score': tensor(0.7756)},
 {'index': [3, 218], 'score': tensor(0.7756)},
 {'index': [4, 1381], 'score': tensor(0.7755)},
 {'index': [3, 71], 'score': tensor(0.7749)},
 {'index': [0, 820], 'score': tensor(0.7745)},
 {'index': [3, 342], 'score': tensor(0.7745)},
 {'index': [3, 1051], 'score': tensor(0.7744)},
 {'index': [4, 1367], 'score': tensor(0.7743)},
 {'index': [3, 1470], 'score': tensor(0.7743)},
 {'index': [4, 1501], 'score': tensor(0.7742)},
 {'index': [3, 800], 'score': tensor(0.7740)},
 {'index': [3, 1311], 'score': tensor(0.7738)},
 {'index': [0, 1238], 'score': tensor(0.7736)},
 {'index': [3, 656], 'score': tensor(0.7735)},
 {'index': [3, 215], 'score': tensor(0.7731)},
 {'index': [4, 804], 'score': tensor(0.7727)},
 {'index': [3, 702], 'score': tensor(0.7723)},
 {'index': [4, 877], 'score': tensor(0.7721)},
 {'index': [4, 412], 'score': tensor(0.7719)},
 {'index': [3, 156], 'score': tensor(0.7718)},
 {'index': [3, 1182], 'score': tensor(0.7712)},
 {'index': [3, 400], 'score': tensor(0.7710)},
 {'index': [3, 674], 'score': tensor(0.7710)},
 {'index': [3, 1440], 'score': tensor(0.7709)},
 {'index': [1, 993], 'score': tensor(0.7709)},
 {'index': [1, 1387], 'score': tensor(0.7708)},
 {'index': [4, 160], 'score': tensor(0.7706)},
 {'index': [3, 558], 'score': tensor(0.7705)},
 {'index': [3, 1360], 'score': tensor(0.7704)},
 {'index': [3, 1113], 'score': tensor(0.7704)},
 {'index': [4, 1069], 'score': tensor(0.7702)},
 {'index': [3, 695], 'score': tensor(0.7702)},
 {'index': [3, 552], 'score': tensor(0.7702)},
 {'index': [3, 607], 'score': tensor(0.7700)},
 {'index': [3, 997], 'score': tensor(0.7695)},
 {'index': [4, 1435], 'score': tensor(0.7695)},
 {'index': [3, 167], 'score': tensor(0.7694)},
 {'index': [4, 1393], 'score': tensor(0.7692)},
 {'index': [3, 1382], 'score': tensor(0.7691)},
 {'index': [3, 771], 'score': tensor(0.7689)},
 {'index': [3, 133], 'score': tensor(0.7689)},
 {'index': [6, 1038], 'score': tensor(0.7689)},
 {'index': [0, 163], 'score': tensor(0.7688)},
 {'index': [1, 772], 'score': tensor(0.7686)},
 {'index': [4, 1363], 'score': tensor(0.7684)},
 {'index': [4, 1543], 'score': tensor(0.7683)},
 {'index': [1, 898], 'score': tensor(0.7682)},
 {'index': [3, 898], 'score': tensor(0.7681)},
 {'index': [3, 1140], 'score': tensor(0.7677)},
 {'index': [3, 1537], 'score': tensor(0.7677)},
 {'index': [3, 1553], 'score': tensor(0.7674)},
 {'index': [3, 1040], 'score': tensor(0.7672)},
 {'index': [4, 385], 'score': tensor(0.7672)},
 {'index': [4, 1529], 'score': tensor(0.7671)},
 {'index': [4, 7], 'score': tensor(0.7671)},
 {'index': [4, 905], 'score': tensor(0.7669)},
 {'index': [4, 1273], 'score': tensor(0.7669)},
 {'index': [4, 1222], 'score': tensor(0.7668)},
 {'index': [3, 393], 'score': tensor(0.7668)},
 {'index': [3, 905], 'score': tensor(0.7667)},
 {'index': [3, 1400], 'score': tensor(0.7665)},
 {'index': [4, 54], 'score': tensor(0.7664)},
 {'index': [3, 305], 'score': tensor(0.7664)},
 {'index': [4, 795], 'score': tensor(0.7663)},
 {'index': [4, 1603], 'score': tensor(0.7662)},
 {'index': [3, 1282], 'score': tensor(0.7662)},
 {'index': [1, 976], 'score': tensor(0.7661)},
 {'index': [0, 747], 'score': tensor(0.7660)},
 {'index': [4, 1068], 'score': tensor(0.7659)},
 {'index': [1, 1385], 'score': tensor(0.7658)},
 {'index': [0, 1041], 'score': tensor(0.7656)},
 {'index': [0, 836], 'score': tensor(0.7654)},
 {'index': [4, 677], 'score': tensor(0.7653)},
 {'index': [4, 1217], 'score': tensor(0.7653)},
 {'index': [3, 598], 'score': tensor(0.7651)},
 {'index': [3, 1371], 'score': tensor(0.7649)},
 {'index': [2, 914], 'score': tensor(0.7649)},
 {'index': [4, 1117], 'score': tensor(0.7649)},
 {'index': [0, 579], 'score': tensor(0.7646)},
 {'index': [4, 715], 'score': tensor(0.7646)},
 {'index': [3, 1474], 'score': tensor(0.7645)},
 {'index': [1, 236], 'score': tensor(0.7642)},
 {'index': [4, 444], 'score': tensor(0.7641)},
 {'index': [3, 485], 'score': tensor(0.7641)},
 {'index': [4, 700], 'score': tensor(0.7639)},
 {'index': [3, 92], 'score': tensor(0.7639)},
 {'index': [4, 230], 'score': tensor(0.7637)},
 {'index': [3, 984], 'score': tensor(0.7636)},
 {'index': [0, 460], 'score': tensor(0.7635)},
 {'index': [2, 1172], 'score': tensor(0.7634)},
 {'index': [3, 612], 'score': tensor(0.7633)},
 {'index': [4, 903], 'score': tensor(0.7632)},
 {'index': [3, 5], 'score': tensor(0.7630)},
 {'index': [4, 834], 'score': tensor(0.7630)},
 {'index': [3, 803], 'score': tensor(0.7628)},
 {'index': [2, 829], 'score': tensor(0.7625)},
 {'index': [3, 1178], 'score': tensor(0.7623)},
 {'index': [1, 1064], 'score': tensor(0.7622)},
 {'index': [0, 132], 'score': tensor(0.7621)},
 {'index': [4, 168], 'score': tensor(0.7620)},
 {'index': [0, 472], 'score': tensor(0.7618)},
 {'index': [1, 853], 'score': tensor(0.7615)},
 {'index': [3, 1107], 'score': tensor(0.7613)},
 {'index': [3, 831], 'score': tensor(0.7613)},
 {'index': [3, 615], 'score': tensor(0.7611)},
 {'index': [3, 858], 'score': tensor(0.7610)},
 {'index': [1, 235], 'score': tensor(0.7609)},
 {'index': [0, 1085], 'score': tensor(0.7608)},
 {'index': [3, 191], 'score': tensor(0.7608)},
 {'index': [3, 1119], 'score': tensor(0.7604)},
 {'index': [3, 903], 'score': tensor(0.7603)},
 {'index': [1, 147], 'score': tensor(0.7602)},
 {'index': [3, 1357], 'score': tensor(0.7602)},
 {'index': [3, 228], 'score': tensor(0.7601)},
 {'index': [4, 318], 'score': tensor(0.7600)},
 {'index': [3, 411], 'score': tensor(0.7600)},
 {'index': [4, 227], 'score': tensor(0.7599)},
 {'index': [4, 1477], 'score': tensor(0.7599)},
 {'index': [4, 1150], 'score': tensor(0.7599)},
 {'index': [4, 88], 'score': tensor(0.7596)},
 {'index': [3, 1437], 'score': tensor(0.7595)},
 {'index': [3, 577], 'score': tensor(0.7595)},
 {'index': [0, 1471], 'score': tensor(0.7593)},
 {'index': [3, 312], 'score': tensor(0.7591)},
 {'index': [4, 202], 'score': tensor(0.7590)},
 {'index': [4, 1513], 'score': tensor(0.7590)},
 {'index': [3, 1473], 'score': tensor(0.7589)},
 {'index': [4, 957], 'score': tensor(0.7589)},
 {'index': [4, 162], 'score': tensor(0.7588)},
 {'index': [3, 837], 'score': tensor(0.7588)},
 {'index': [0, 162], 'score': tensor(0.7588)},
 {'index': [4, 1303], 'score': tensor(0.7588)},
 {'index': [4, 71], 'score': tensor(0.7586)},
 {'index': [3, 1313], 'score': tensor(0.7584)},
 {'index': [3, 1466], 'score': tensor(0.7584)},
 {'index': [1, 529], 'score': tensor(0.7583)},
 {'index': [3, 1340], 'score': tensor(0.7582)},
 {'index': [4, 1293], 'score': tensor(0.7580)},
 {'index': [0, 580], 'score': tensor(0.7580)},
 {'index': [3, 1169], 'score': tensor(0.7579)},
 {'index': [4, 121], 'score': tensor(0.7578)},
 {'index': [4, 1051], 'score': tensor(0.7576)},
 {'index': [4, 645], 'score': tensor(0.7576)},
 {'index': [4, 1170], 'score': tensor(0.7575)},
 {'index': [4, 1402], 'score': tensor(0.7575)},
 {'index': [3, 119], 'score': tensor(0.7573)},
 {'index': [4, 1110], 'score': tensor(0.7568)},
 {'index': [4, 64], 'score': tensor(0.7565)},
 {'index': [3, 715], 'score': tensor(0.7565)},
 {'index': [4, 192], 'score': tensor(0.7565)},
 {'index': [4, 615], 'score': tensor(0.7565)},
 {'index': [0, 704], 'score': tensor(0.7564)},
 {'index': [3, 1500], 'score': tensor(0.7563)},
 {'index': [0, 1217], 'score': tensor(0.7559)},
 {'index': [3, 707], 'score': tensor(0.7557)},
 {'index': [4, 1359], 'score': tensor(0.7557)},
 {'index': [3, 670], 'score': tensor(0.7557)},
 {'index': [2, 436], 'score': tensor(0.7556)},
 {'index': [1, 82], 'score': tensor(0.7555)},
 {'index': [4, 977], 'score': tensor(0.7553)},
 {'index': [4, 1385], 'score': tensor(0.7553)},
 {'index': [4, 416], 'score': tensor(0.7553)},
 {'index': [6, 846], 'score': tensor(0.7550)},
 {'index': [0, 765], 'score': tensor(0.7550)},
 {'index': [3, 688], 'score': tensor(0.7546)},
 {'index': [3, 1596], 'score': tensor(0.7545)},
 {'index': [4, 356], 'score': tensor(0.7544)},
 {'index': [2, 625], 'score': tensor(0.7543)},
 {'index': [3, 1071], 'score': tensor(0.7543)},
 {'index': [4, 1114], 'score': tensor(0.7543)},
 {'index': [2, 302], 'score': tensor(0.7543)},
 {'index': [0, 1514], 'score': tensor(0.7542)},
 {'index': [3, 712], 'score': tensor(0.7540)},
 {'index': [2, 964], 'score': tensor(0.7539)},
 {'index': [3, 118], 'score': tensor(0.7539)},
 {'index': [4, 1504], 'score': tensor(0.7539)},
 {'index': [1, 137], 'score': tensor(0.7536)},
 {'index': [3, 82], 'score': tensor(0.7535)},
 {'index': [4, 748], 'score': tensor(0.7534)},
 {'index': [4, 1440], 'score': tensor(0.7533)},
 {'index': [0, 744], 'score': tensor(0.7533)},
 {'index': [3, 1364], 'score': tensor(0.7533)},
 {'index': [0, 1196], 'score': tensor(0.7532)},
 {'index': [3, 210], 'score': tensor(0.7531)},
 {'index': [3, 1109], 'score': tensor(0.7531)},
 {'index': [0, 464], 'score': tensor(0.7530)},
 {'index': [3, 966], 'score': tensor(0.7529)},
 {'index': [4, 978], 'score': tensor(0.7529)},
 {'index': [3, 554], 'score': tensor(0.7529)},
 {'index': [1, 230], 'score': tensor(0.7528)},
 {'index': [3, 1175], 'score': tensor(0.7528)},
 {'index': [4, 465], 'score': tensor(0.7526)},
 {'index': [1, 446], 'score': tensor(0.7525)},
 {'index': [4, 954], 'score': tensor(0.7525)},
 {'index': [3, 444], 'score': tensor(0.7524)},
 {'index': [4, 819], 'score': tensor(0.7522)},
 {'index': [4, 1243], 'score': tensor(0.7522)},
 {'index': [3, 917], 'score': tensor(0.7521)},
 {'index': [3, 621], 'score': tensor(0.7521)},
 {'index': [0, 1101], 'score': tensor(0.7520)},
 {'index': [1, 1366], 'score': tensor(0.7519)},
 {'index': [4, 552], 'score': tensor(0.7516)},
 {'index': [0, 550], 'score': tensor(0.7516)},
 {'index': [3, 681], 'score': tensor(0.7515)},
 {'index': [3, 645], 'score': tensor(0.7515)},
 {'index': [3, 703], 'score': tensor(0.7514)},
 {'index': [4, 710], 'score': tensor(0.7514)},
 {'index': [3, 822], 'score': tensor(0.7513)},
 {'index': [1, 566], 'score': tensor(0.7512)},
 {'index': [0, 1416], 'score': tensor(0.7511)},
 {'index': [3, 310], 'score': tensor(0.7510)},
 {'index': [2, 847], 'score': tensor(0.7509)},
 {'index': [3, 500], 'score': tensor(0.7508)},
 {'index': [3, 1006], 'score': tensor(0.7507)},
 {'index': [0, 161], 'score': tensor(0.7507)},
 {'index': [1, 1357], 'score': tensor(0.7506)},
 {'index': [4, 1132], 'score': tensor(0.7506)},
 {'index': [3, 160], 'score': tensor(0.7504)},
 {'index': [4, 99], 'score': tensor(0.7504)},
 {'index': [3, 302], 'score': tensor(0.7504)},
 {'index': [3, 147], 'score': tensor(0.7503)},
 {'index': [1, 1455], 'score': tensor(0.7503)},
 {'index': [3, 974], 'score': tensor(0.7503)},
 {'index': [4, 1596], 'score': tensor(0.7501)},
 {'index': [1, 705], 'score': tensor(0.7501)},
 {'index': [4, 1010], 'score': tensor(0.7496)},
 {'index': [4, 895], 'score': tensor(0.7494)},
 {'index': [3, 106], 'score': tensor(0.7492)},
 {'index': [3, 625], 'score': tensor(0.7491)},

In [ ]:
for i in range(
    cosine_scores.shape[0]):

  print(f"Recommended for {my_perfumes.iloc[i,0]}:")
  my_pairs = []

  for j in range(
      cosine_scores.shape[1]):
    my_pairs.append(
        {
            'index': j,
            'score': cosine_scores[i][j]
        }
    )
    my_sorted_pairs = sorted(
        my_pairs,
        key=lambda x: x['score'],
        reverse=True
    )

  for no, pair in enumerate(my_sorted_pairs[:20]):
    print(f" {no+1}. {df.iloc[pair['index'], 0]} (Score: {pair['score']:.3f})")
  print('\n')

Recommended for Jo Malone - English Pear & Freesia:
 1. Alexandre. J - Silver Ombre Eau de Parfum (Score: 0.801)
 2. Montale - Starry Nights Eau de Parfum (Score: 0.788)
 3. BDK Parfums - Bouquet de Hongrie Eau de Parfum (Score: 0.788)
 4. Jovoy Paris - Psychedelique Eau de Parfum (Score: 0.788)
 5. L'Artisan Parfumeur - Champ de Fleurs Eau de Cologne (Score: 0.783)
 6. The Beautiful Mind Series - Precision & Grace Eau de Parfum (Score: 0.778)
 7. Fort & Manle - Amber Absolutely Eau de Parfum (Score: 0.777)
 8. Eight and Bob - Champs de Provence Eau de Parfum (Score: 0.775)
 9. PARFUMS DE NICOLAI - Rose Oud Eau de Parfum (Score: 0.774)
 10. Alexandre. J - Rose Oud Eau de Parfum (Score: 0.769)
 11. Fort & Manle - Impressions de Giverny Eau de Parfum (Score: 0.766)
 12. Xerjoff - V - Accento Eau de Parfum (Score: 0.766)
 13. Pierre Guillaume Paris, Parfumerie Generale - Neroli Ad Astra Eau de Parfum (Score: 0.765)
 14. J-Scent - Yawahada (Soft Skin) Eau de Parfum (Score: 0.765)
 15. Profumi del Forte - Corpi Caldi Eau de Parfum (Score: 0.763)
 16. Farmacia SS. Annunziata dal 1561 - Verde di Persia Parfum Concentration (Score: 0.762)
 17. Fragrance du Bois - Brume du Matin Eau de Parfum (Score: 0.762)
 18. Perris Monte Carlo - Bois d'Oud Eau de Parfum (Score: 0.761)
 19. Juliette Has a Gun - Midnight Oud Eau de Parfum (Score: 0.759)
 20. Alexandre. J - Black Muscs Eau de Parfum (Score: 0.759)


Recommended for Jo Malone - Myrrh & Tonka:
 1. Parfum d'Empire - Fougere Bengale Eau de Parfum (Score: 0.858)
 2. Tauer Perfumes - Une Rose Vermeille Eau de Parfum (Score: 0.835)
 3. Xerjoff - 1861 - Naxos Eau de Parfum (Score: 0.831)
 4. PARFUMS DE NICOLAI - Amber Oud Eau de Parfum (Score: 0.828)
 5. Reims Parfums - L'Eau des Sacres (Score: 0.804)
 6. Keiko Mecheri - Isles Lointaines Eau de Parfum (Score: 0.803)
 7. Sarah Horowitz Parfums - Perfect Coconut Milk Eau de Parfum (Score: 0.799)
 8. PARFUMS DE NICOLAI - Patchouli Sublime Elixir de Parfum (Score: 0.798)
 9. Profumum - Dolce Acqua Eau de Parfum (Score: 0.798)
 10. Serge Lutens - Un Bois Vanille Eau de Parfum (Score: 0.794)
 11. Farmacia SS. Annunziata dal 1561 - Talc Gourmand Eau de Parfum (Score: 0.793)
 12. Gallivant - Istanbul Eau de Parfum (Score: 0.793)
 13. Essential Parfums - The Musc Eau de Parfum (Score: 0.788)
 14. PARFUMS DE NICOLAI - Vanille Tonka Eau de Parfum (Score: 0.786)
 15. 4160 Tuesdays - Centrepiece Eau de Parfum (Score: 0.786)
 16. A Lab on Fire - A Blvd. Called Sunset Eau de Parfum (Score: 0.783)
 17. Serge Lutens - Datura Noir Eau de Parfum (Score: 0.783)
 18. Phaedon - Sable & Soleil Eau de Parfum (Score: 0.771)
 19. Aroma M - Geisha Rouge - Eau de Parfum (Score: 0.771)
 20. Fort & Manle - Bojnokopff Eau de Parfum (Score: 0.769)


Recommended for Jo Malone - Oud & Bergamot:
 1. Comme des Garcons: Cologne - Citrico (Score: 0.851)
 2. The House Of Oud - Cypress Shade Eau de Parfum (Score: 0.765)
 3. Xerjoff - Blue Hope Eau de Parfum (Score: 0.763)
 4. L'Artisan Parfumeur - Au Bord De L'Eau Eau de Cologne (Score: 0.763)
 5. Gravel - Across The Ocean Eau de Parfum (Score: 0.756)
 6. Xerjoff - Casamorati - Mefisto Gentiluomo Eau de Parfum (Score: 0.754)
 7. Electimuss - Trajan Eau de Parfum (Score: 0.754)
 8. Rania J. - Oud Assam Eau de Parfum (Score: 0.754)
 9. Ormonde Jayne - Isfarkand Eau de Parfum (Score: 0.751)
 10. Mancera - Wild Rose Aoud Eau de Parfum (Score: 0.748)
 11. Le Labo - Bergamote 22 Eau de Parfum (Score: 0.747)
 12. Fort & Manle - Fatih Sultan Mehmed Eau de Parfum (Score: 0.745)
 13. Nobile 1942 - La Danza delle Libellule Eau de Parfum (Score: 0.740)
 14. Boadicea the Victorious - Lavish Parfum (Score: 0.739)
 15. Eight and Bob - Eight and Bob Eau de Parfum (Score: 0.734)
 16. Alexandre. J - Black Muscs Eau de Parfum (Score: 0.732)
 17. Nobile 1942 - Estroverso Eau de Parfum (Score: 0.731)
 18. Xerjoff - V - Erba Pura Eau de Parfum (Score: 0.731)
 19. Xerjoff - Uden Overdose Parfum (Score: 0.730)
 20. Bortnikoff - Moss Cologne Eau de Parfum (Score: 0.727)


Recommended for Guerlain - Néroli Outrenoir:
 1. ANFAS - Purple Sakan (Score: 0.854)
 2. MEMO - Winter Palace Eau de Parfum (Score: 0.852)
 3. Penhaligons - Halfeti Eau de Parfum (Score: 0.850)
 4. Parfums MDCI - Le Barbier de Tanger Eau de Parfum (Score: 0.848)
 5. Nobile 1942 - Perdizione Eau de Parfum (Score: 0.846)
 6. The House Of Oud - Just Before Eau de Parfum (Score: 0.845)
 7. HEELEY - Oranges and Lemons Say The Bells of St. Clements Eau de Parfum (Score: 0.841)
 8. Kemi - Aurum Eau de Parfum (Score: 0.840)
 9. Une Nuit Nomade - Fleur des Fleurs Eau de Parfum (Score: 0.838)
 10. Roja Parfums - Creation-E Parfum Cologne (Score: 0.838)
 11. Jovoy Paris - Remember Me Eau de Parfum (Score: 0.834)
 12. J-Scent - Shaft of Light Eau de Parfum (Score: 0.831)
 13. Parfums de Marly - Layton EXCLUSIF Eau de Parfum (Score: 0.831)
 14. Ex Nihilo - Musc Infini Eau de Parfum (Score: 0.829)
 15. Majda Bekkali - Fusion Sacree - Obscur Eau de Parfum (Score: 0.828)
 16. Bortnikoff - Coup de Foudre Eau de Parfum (Score: 0.823)
 17. Parfums MDCI - Les Indes Galantes Eau de Parfum (Score: 0.820)
 18. Electimuss - Rhodanthe Eau de Parfum (Score: 0.818)
 19. Costume National - Homme Eau de Parfum (Score: 0.818)
 20. Parfums de Marly - Layton Eau de Parfum (Score: 0.816)


Recommended for Guerlain - Épices Volées:
 1. Costume National - Homme Eau de Parfum (Score: 0.856)
 2. Roja Parfums - Creation-E Parfum Cologne (Score: 0.845)
 3. Parfums MDCI - Les Indes Galantes Eau de Parfum (Score: 0.839)
 4. Boadicea the Victorious - Ardent Eau de Parfum (Score: 0.833)
 5. Timothy Han Edition Perfumes - She Came to Stay Eau de Parfum (Score: 0.831)
 6. Xerjoff - Pikovaya Dama Eau de Parfum (Score: 0.829)
 7. Divine - L'Etre Aime - Homme Eau de Parfum (Score: 0.829)
 8. Houbigant - Fougere Royale Eau de Parfum (Score: 0.827)
 9. Bogue Profumo - O/E Eau de Parfum (Score: 0.822)
 10. Maitre Parfumeur et Gantier - Ambre Mythique Eau de Parfum (Score: 0.820)
 11. Tauer Perfumes - Incense Rose Eau de Parfum (Score: 0.819)
 12. Carthusia - 1681 Eau de Parfum (Score: 0.817)
 13. Ex Nihilo - French Affair Eau de Parfum (Score: 0.817)
 14. Olivier Durbano - Rock Crystal Eau de Parfum (Score: 0.816)
 15. Montale - Oud Dream Eau de Parfum (Score: 0.815)
 16. Santa Eulalia - Citric Parfum (Score: 0.814)
 17. Thameen - Sceptre (Score: 0.812)
 18. Roja Parfums - Scandal Parfum Cologne (Score: 0.810)
 19. Parfums MDCI - Le Barbier de Tanger Eau de Parfum (Score: 0.810)
 20. Fragrance du Bois - Velvet Amber (Score: 0.809)


Recommended for Guerlain - Aqua Allegoria Nerolia Vetiver Eau de Toilette:
 1. Liquides Imaginaires - Tellus Eau de Parfum (Score: 0.614)
 2. BYREDO - Oud Immortel Eau de Parfum (Score: 0.606)
 3. Vilhelm Parfumerie - Basilico & Fellini Eau de Parfum (Score: 0.602)
 4. Nanadebary - Green Eau de Parfum (Score: 0.600)
 5. Reims Parfums - L'Eau de Reims (Score: 0.584)
 6. Atelier Cologne - Bois Blonds Cologne Absolue (Score: 0.583)
 7. Aesop - Tacit Eau de Parfum (Score: 0.580)
 8. Di Ser - Kazehikaru Eau de Parfum (Score: 0.577)
 9. Essential Parfums - Mon Vetiver Eau de Parfum (Score: 0.575)
 10. Hiram Green Perfumes - Slowdive Eau de Parfum (Score: 0.574)
 11. Aroma M - Camellia Eau de Parfum (Score: 0.573)
 12. Il Profumo - Musc Bleu Eau de Parfum (Score: 0.571)
 13. Nobile 1942 - Ambra Nobile Eau de Parfum (Score: 0.570)
 14. Mona di Orio - Musc - Les Nombres d'Or Eau de Parfum (Score: 0.568)
 15. YOSH - Ginger Ciao Eau de Parfum (Score: 0.560)
 16. Liquides Imaginaires - Dom Rosa Eau de Parfum (Score: 0.556)
 17. Neela Vermeire Creations - Ashoka Eau de Parfum (Score: 0.555)
 18. Jovoy Paris - Private Label Eau de Parfum (Score: 0.555)
 19. Rania J. - Cuir Andalou Eau de Parfum (Score: 0.549)
 20. Amouage - Figment Man Eau de Parfum (Score: 0.549)


Recommended for Chloe Eau de Parfum:
 1. Caron - French Cancan - Eau de Parfum (Score: 0.769)
 2. Ormonde Jayne - Frangipani Eau de Parfum (Score: 0.755)
 3. Floris London - 1962 Eau de Parfum (Score: 0.741)
 4. Parfums MDCI - Rose de Siwa Eau de Parfum (Score: 0.727)
 5. PARFUMS DE NICOLAI - Rose Oud Eau de Parfum (Score: 0.726)
 6. J-Scent - Koiame Eau de Parfum (Score: 0.724)
 7. Xerjoff - 1861 - Renaissance Eau de Parfum (Score: 0.718)
 8. Dusita - Fleur de Lalita Eau de Parfum (Score: 0.716)
 9. Xerjoff - Oud Stars - Alexandria II Eau de Parfum (Score: 0.715)
 10. J-Scent - Hakka Eau de Parfum (Score: 0.709)
 11. Fort & Manle - Confessions of a Garden Gnome Eau de Parfum (Score: 0.708)
 12. Thomas Kosmala - No. 5 Frenesie Eau de Parfum (Score: 0.707)
 13. BYREDO - Inflorescence Eau de Parfum (Score: 0.707)
 14. Charenton Macerations - Asphalt Rainbow Eau de Parfum (Score: 0.704)
 15. Carthusia - Fiori di Capri Parfum (Score: 0.702)
 16. Carthusia - Fiori di Capri Eau de Parfum (Score: 0.702)
 17. Profumi del Forte - Versilia Aurum Eau de Parfum (Score: 0.701)
 18. Parfum Satori - Hana Hiraku Eau de Parfum (Score: 0.701)
 19. Penhaligons - Quercus Cologne (Score: 0.701)
 20. Fragrance du Bois - Brume du Matin Eau de Parfum (Score: 0.700)

# **What is BERT?**
**BERT (Bidirectional Encoder Representations from Transformers)** adalah model representasi bahasa yang dirancang oleh para peneliti di Google AI language.

**What does BERT do?**
  * berbeda dengan model pre-trained lainnya sebelum BERT, seperti model berbasis fitur ELMo dan model fine-tuning GPT yang melakukan **unidirectional language representation learning,** BERT melatih representasi **bidirectional representations** yang mendalam dari teks tanpa label dengan mengkondisikan secara bersamaan pada konteks kiri dan kanan disemua lapisan.

  * BERT adalah model representasi berbais fine-tuning pertama yang mencapai performa terbaik pada berbagai tugas tingkat kalimat seperti parafrase dan tugas tingkat token seperti **Named Entity Recognition (NER)**, mengungguli banyak arsitektur spesifik tugas.

  * BERT memajukan teknologi terkini untuk 11 tugas NLP. kode dan model pre-trained tersedia: [teks link](https://github.com/google-research/bert.)

# **How Does BERT Work?:**

  * **Masked LM:** sebelum kalimat dimasukkan ke BERT, 15% dari token input dalam setiap kalimat ditutupi secara acak dengan token **[MASK]**. model kemudian memprediksi token yang ditutupi tersebut berdasarkan konteks **left-to-right** atau **right-to-left** yang diberikan oleh token lain yang tidak ditutupi dalam kalimat. hal ini dapat memungkinkan untuk mendapatkan model **bidirectional pretrained.**
  * **Next Sentence Prediction:** selama proses pelatihan BERT, model akan menerima pasangan kalimat sebagai input. saat memilih kalimat A dan B untuk setiap contoh pelatihan 50% kemungkinan B adalah kalimat berikutnya yang sebenarnya dari A dalam dokumen asli dan 50% kemungkinan B adalah kalimat acak dari korpus. model belajar untuk memprediksi apakah B adalah kalimat berikutnya yang sebenarnya dari A. hal ini memungkinkan kita untuk mendapatkan model yang memahami hubungan antara dua kalimat.